Maxstache parentDir
yoshuawuyts/copy-template-dir pull request #11
Opened 2018-02-21 23:29 UTC by ggPeti

Currently the library breaks because `outFile`'s path is maxstached, but the directory created for it is not.

2018-03-15 17:34 UTC, ammmze commented
I'm also looking for support for this as well. I'm using this library in a react component generation process and I want to create a directory using a variable name, but it just errors out.

2018-03-15 17:37 UTC, ggPeti commented
@yoshuawuyts please review :)

2018-03-15 20:59 UTC, loklaan requested changes
This is something I seemed to have missed in [v1.3.0](https://github.com/yoshuawuyts/copy-template-dir/releases/tag/v1.3.0)... 😢 

Thanks for going to the effort of making this PR.

Looks good, but **needs tests**! I'll jump back in when you get around to adding them 🙏

2018-03-16 17:33 UTC, ammmze commented
@loklaan we've got a test added to verify variables in the directories. please take look when you have time 🙏

2018-03-21 04:16 UTC, loklaan approved these changes

2018-03-21 04:18 UTC, merged

2018-03-21 04:27 UTC, loklaan commented
@ggPeti @ammmze Thanks, folks! 🎉 
https://github.com/yoshuawuyts/copy-template-dir/releases/tag/v1.4.0